Python=3.9.5
Platform=Linux-5.11.21-200.fc33.x86_64-x86_64-with-glibc2.32
cardano-node=1.27.0
cardano-node.rev=4783593c35b8c4dcc5a538ce8c836d0fdafd8369
ghc=ghc-8.10
cardano-node-tests.rev=8f3be0a7ad6354723bcd46ad1bae2fc5efe2672b
cardano-node-tests.url=https://github.com/input-output-hk/cardano-node-tests/tree/8f3be0a7ad6354723bcd46ad1bae2fc5efe2672b
HAS_DBSYNC=False
CARDANO_NODE_SOCKET_PATH=/home/martink/Source/repos/cardano-node1/state-cluster0/relay1.socket
cardano-cli.exe=/nix/store/0s3l4fvx6pc6r2w4xj5ys3p0si65sdzx-cardano-cli-exe-cardano-cli-1.27.0/bin/cardano-cli
