Python=3.9.5
Platform=Linux-5.12.13-300.fc34.x86_64-x86_64-with-glibc2.33
cardano-node=1.27.0
cardano-node.rev=7cf540dafa0ca496526e0614fa3ef6262e85c70d
ghc=ghc-8.10
cardano-node-tests.rev=dc97f973d4fc168c53fe9447088a334a26e2f903
cardano-node-tests.url=https://github.com/input-output-hk/cardano-node-tests/tree/dc97f973d4fc168c53fe9447088a334a26e2f903
CARDANO_NODE_SOCKET_PATH=/home/martink/Source/repos/cardano-node1/state-cluster0/relay1.socket
cardano-cli.exe=/nix/store/kza6vyjiw4h5wkx93h4fhyjlwhkxz9db-cardano-cli-exe-cardano-cli-1.27.0/bin/cardano-cli
HAS_DBSYNC=False
