Python=3.9.5
Platform=Linux-5.11.21-200.fc33.x86_64-x86_64-with-glibc2.32
cardano-node=1.27.0
cardano-node.rev=d8eee10f7b680cdea06c562e054feee237eb1d09
ghc=ghc-8.10
cardano-node-tests.rev=4cf06951aa8e6e02334d48676150f8d830b94f12
cardano-node-tests.url=https://github.com/input-output-hk/cardano-node-tests/tree/4cf06951aa8e6e02334d48676150f8d830b94f12
HAS_DBSYNC=False
CARDANO_NODE_SOCKET_PATH=/home/martink/Source/repos/cardano-node1/state-cluster0/relay1.socket
cardano-cli.exe=/nix/store/za6xxja9qj4n6a9alk54xwj0353hw0dl-cardano-cli-exe-cardano-cli-1.27.0/bin/cardano-cli
