Python=3.9.5
Platform=Linux-5.11.21-200.fc33.x86_64-x86_64-with-glibc2.32
cardano-node=1.27.0
cardano-node.rev=d902c08b4a991a4ca437e561b638ad1013e78cf0
ghc=ghc-8.10
cardano-node-tests.rev=19e754ac59505809871ab12ce2efb594271cb851
cardano-node-tests.url=https://github.com/input-output-hk/cardano-node-tests/tree/19e754ac59505809871ab12ce2efb594271cb851
HAS_DBSYNC=False
CARDANO_NODE_SOCKET_PATH=/home/martink/Source/repos/cardano-node1/state-cluster0/relay1.socket
cardano-cli.exe=/nix/store/bikr8b8z8i6hzm00jj46bk6y11czqckz-cardano-cli-exe-cardano-cli-1.27.0/bin/cardano-cli
